### ISSUE TITLE
Collection Params Update API fails with errors. 

### ISSUE THREAD

**Issue by dingusagar** [qdrant/qdrant#1013]
I am using an older version of qdrant  - v0.6.0 in production.  

Was tying to the Collection params API to update the memmap_threshold like this. 
```
curl --location --request PATCH 'http://localhost:6333/collections/product_text_embeddings__10203' \
--header 'Content-Type: application/json' \
--data-raw '{
  "optimizers_config": {
    "memmap_threshold": 100
  }
}'
```

But I can see the following errors in qdrant logs. 
```
[2022-09-14T06:28:32Z ERROR collection::update_handler] Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/0942243f-6b69-4efa-9817-e07455ed3ff1.deleted, error: Directory not empty (os error 39)
thread 'collection-product_text_embeddings__10203-shard-0-optimizer-9' panicked at 'Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/0942243f-6b69-4efa-9817-e07455ed3ff1.deleted, error: Directory not empty (os error 39)', lib/collection/src/update_handler.rs:231:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-09-14T06:28:33Z ERROR collection::update_handler] Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/bedc20f9-758c-4187-a95b-7930f99565c9.deleted, error: Directory not empty (os error 39)
thread 'collection-product_text_embeddings__10203-shard-0-optimizer-10' panicked at 'Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/bedc20f9-758c-4187-a95b-7930f99565c9.deleted, error: Directory not empty (os error 39)', lib/collection/src/update_handler.rs:231:37
[2022-09-14T06:28:34Z ERROR collection::update_handler] Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/aa2c826f-e857-4f1d-873b-1e7838cc6a15.deleted, error: Directory not empty (os error 39)
thread 'collection-product_text_embeddings__10203-shard-0-optimizer-8' panicked at 'Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/aa2c826f-e857-4f1d-873b-1e7838cc6a15.deleted, error: Directory not empty (os error 39)', lib/collection/src/update_handler.rs:231:37
[2022-09-14T06:28:36Z ERROR collection::update_handler] Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/9744043a-ce03-4166-b465-45327a947234.deleted, error: Directory not empty (os error 39)
thread 'collection-product_text_embeddings__10203-shard-0-optimizer-6' panicked at 'Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/9744043a-ce03-4166-b465-45327a947234.deleted, error: Directory not empty (os error 39)', lib/collection/src/update_handler.rs:231:37
[2022-09-14T06:28:36Z ERROR collection::update_handler] Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/82c3e7f3-b45e-4a25-a572-087985d4d89e.deleted, error: Directory not empty (os error 39)
thread 'collection-product_text_embeddings__10203-shard-0-optimizer-7' panicked at 'Optimization error: Service internal error: Can't remove segment data at ./storage/collections/product_text_embeddings__10203/segments/82c3e7f3-b45e-4a25-a572-087985d4d89e.deleted, error: Directory not empty (os error 39)', lib/collection/src/update_handler.rs:231:37

```

Wanted to check if this is some bug fixed in the newer versions? If so I guess I would have to upgrade to the newer version.

**Comment by generall** [comment]
Assuming the error is fixed in the latest version. Please feel free to re-open it, if the error appears again
