### ISSUE TITLE
Test test_indexing_optimizer undefined according to cargo-careful

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#1330]
Running our tests with [cargo-careful](https://github.com/RalfJung/cargo-careful) yields an error for the optimizer unsafe code.

```rust
fn transmute_from_u8_mut<T>(data: &mut [u8]) -> &mut [T] {
    let len = data.len() / size_of::<T>();
    let ptr = data.as_mut_ptr() as *mut T;
    unsafe { std::slice::from_raw_parts_mut(ptr, len) }
}
```

## Current Behavior

```
thread 'collection_manager::optimizers::indexing_optimizer::tests::test_indexing_optimizer' panicked at 'unsafe precondition(s) violated: slice::from_raw_parts_mut requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`', /home/agourlay/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:89:58
stack backtrace:
   0:     0x5632b6d6503a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbec85491f3954403
   1:     0x5632b6d90378 - core::fmt::write::h13bcc8cc3755c9d6
   2:     0x5632b6d42e61 - std::io::Write::write_fmt::h71167d7254fabb92
   3:     0x5632b6d64e35 - std::sys_common::backtrace::print::hfa7b651949bd5b7a
   4:     0x5632b6d4c607 - std::panicking::default_hook::{{closure}}::h68c8e294443874e4
   5:     0x5632b6d4c311 - std::panicking::default_hook::he6be6088d383148c
   6:     0x5632b5e53c16 - test::test_main::{{closure}}::hefa30acb114d5d3f
   7:     0x5632b6d4ce22 - std::panicking::rust_panic_with_hook::hb014a4fcd993e852
   8:     0x5632b6d65371 - std::panicking::begin_panic_handler::{{closure}}::h91e6d2b4e877254d
   9:     0x5632b6d6517c - std::sys_common::backtrace::__rust_end_short_backtrace::h45a92eb1246f270e
  10:     0x5632b6d4c8e2 - rust_begin_unwind
  11:     0x5632b57c3d43 - core::panicking::panic_str_nounwind::h2ce7f8ce025ef76b
  12:     0x5632b6391109 - core::slice::raw::from_raw_parts_mut::runtime::hda454492d6e00180
                               at /home/agourlay/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2284:21
  13:     0x5632b6391109 - core::slice::raw::from_raw_parts_mut::h1fbf56bdfbe666e7
                               at /home/agourlay/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2292:13
  14:     0x5632b63c8940 - segment::index::hnsw_index::graph_links::transmute_from_u8_mut::h599f7a30fde94d5b
                               at /home/agourlay/Workspace/qdrant/lib/segment/src/index/hnsw_index/graph_links.rs:24:14
  15:     0x5632b63f1563 - segment::index::hnsw_index::graph_links::GraphLinksConverter::serialize_to::h821810a6240613a3
                               at /home/agourlay/Workspace/qdrant/lib/segment/src/index/hnsw_index/graph_links.rs:242:44
  16:     0x5632b63f1d94 - segment::index::hnsw_index::graph_links::GraphLinksConverter::save_as::hd33d3d367dcd8d88
                               at /home/agourlay/Workspace/qdrant/lib/segment/src/index/hnsw_index/graph_links.rs:287:13
  17:     0x5632b60cb343 - segment::index::hnsw_index::graph_layers_builder::GraphLayersBuilder::into_graph_layers::h31ee4c5903cf575f
                               at /home/agourlay/Workspace/qdrant/lib/segment/src/index/hnsw_index/graph_layers_builder.rs:87:13
  18:     0x5632b615978d - <segment::index::hnsw_index::hnsw::HNSWIndex<TGraphLinks> as segment::index::index_base::VectorIndex>::build_index::hdc349a0b6047797b
                               at /home/agourlay/Workspace/qdrant/lib/segment/src/index/hnsw_index/hnsw.rs:405:27
  19:     0x5632b6086da7 - segment::segment_constructor::segment_builder::SegmentBuilder::build::h7c0722677abab934
                               at /home/agourlay/Workspace/qdrant/lib/segment/src/segment_constructor/segment_builder.rs:191:17
  20:     0x5632b5b32670 - collection::collection_manager::optimizers::segment_optimizer::SegmentOptimizer::build_new_segment::h8450ccead434181e
                               at /home/agourlay/Workspace/qdrant/lib/collection/src/collection_manager/optimizers/segment_optimizer.rs:266:46
  21:     0x5632b5b34cc7 - collection::collection_manager::optimizers::segment_optimizer::SegmentOptimizer::optimize::ha2057453c5e5d40d
                               at /home/agourlay/Workspace/qdrant/lib/collection/src/collection_manager/optimizers/segment_optimizer.rs:405:43
  22:     0x5632b58c7afc - collection::collection_manager::optimizers::indexing_optimizer::tests::test_indexing_optimizer::h8fa5b2d2bef386fc
                               at /home/agourlay/Workspace/qdrant/lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs:484:9
  23:     0x5632b5c5a837 - collection::collection_manager::optimizers::indexing_optimizer::tests::test_indexing_optimizer::{{closure}}::h208537c12f48087d
                               at /home/agourlay/Workspace/qdrant/lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs:379:34
  24:     0x5632b599d765 - core::ops::function::FnOnce::call_once::hc2e96a42c47e9c42
                               at /home/agourlay/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:507:5
  25:     0x5632b5e594cf - test::__rust_begin_short_backtrace::h65928deb3a49d6b5
  26:     0x5632b5e4ef0c - core::ops::function::FnOnce::call_once{{vtable.shim}}::h58a754e3ac19ee95
  27:     0x5632b5e596a0 - test::run_test_in_process::he383a6b63aebf4bb
  28:     0x5632b5e5aece - std::sys_common::backtrace::__rust_begin_short_backtrace::h9c0708ba7bdaf1d2
  29:     0x5632b5e72e28 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2c3e7a4103b8db16
  30:     0x5632b6d35f88 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbd7eaf2d4c3766a3
  31:     0x5632b6d29115 - std::sys::unix::thread::Thread::new::thread_start::h2a9a0fdcc2601a9e
  32:     0x7fb032890402 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  33:     0x7fb03291f590 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  34:                0x0 - <unknown>
thread panicked while panicking. aborting.
error: test failed, to rerun pass `-p collection --lib`

```

## Steps to Reproduce

1. cargo install cargo-careful
2. cargo +nightly careful test --all

## Expected Behavior
Green run.

**Comment by agourlay** [comment]
Adding a bit of test codes confirms the pointer alignment issue.

```diff
diff --git a/lib/segment/src/index/hnsw_index/graph_links.rs b/lib/segment/src/index/hnsw_index/graph_links.rs
index 52d3395e..9cfed8ba 100644
--- a/lib/segment/src/index/hnsw_index/graph_links.rs
+++ b/lib/segment/src/index/hnsw_index/graph_links.rs
@@ -18,10 +18,15 @@ fn transmute_from_u8<T>(data: &[u8]) -> &[T] {
     unsafe { std::slice::from_raw_parts(ptr, len) }
 }
 
+
 fn transmute_from_u8_mut<T>(data: &mut [u8]) -> &mut [T] {
     let len = data.len() / size_of::<T>();
     let ptr = data.as_mut_ptr() as *mut T;
-    unsafe { std::slice::from_raw_parts_mut(ptr, len) }
+
+    unsafe {
+        eprintln!("len: {}, ptr: {:?} aligned: {:?}", len, ptr, ptr.is_aligned());
+        std::slice::from_raw_parts_mut(ptr, len)
+    }
 }
 
 /*
diff --git a/lib/segment/src/lib.rs b/lib/segment/src/lib.rs
index 0d0d3f76..32af1796 100644
--- a/lib/segment/src/lib.rs
+++ b/lib/segment/src/lib.rs
@@ -1,4 +1,5 @@
 #![allow(deprecated)]
+#![feature(pointer_is_aligned)]
 
 pub mod common;
 pub mod entry;
```

Gives the following on the test case

```
len: 4, ptr: 0x7f6e88266000 aligned: true
len: 200, ptr: 0x7f6e88266058 aligned: true
len: 1509, ptr: 0x7f6e88266378 aligned: true
len: 258, ptr: 0x7f6e88267b0c aligned: false
```

**Comment by generall** [comment]
What does the alignment means in this particular case?
