### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [qdrant/qdrant#2354]
Hi!

There is an idea that PGO could help with improving performance even more! There are a lot of examples of different software, where PGO helps a lot with performance - you can check it [here](https://github.com/zamazan4ik/awesome-pgo). E.g. in this list are a lot of databases like PostgreSQL and ClickHouse.

There are several options. I'd appreciate it if you could provide an easy way to build Qdrant with PGO. And experienced users will be able to do it on their own for their own usage scenarios. Another option is to optimize Qdrant build with a generic-enough profile. Providing PGO-optimized binaries could be a trickier task (since it requires preparing a good-enough profile) but as an option would be great to see too. Another idea of how to use PGO - optimize your own cloud-based Qdrant installation.

As an additional optimization way, I suggest taking a look at LLVM BOLT. But from my experience, it would be better to start with PGO and then try to use BOLT.

For the Rust projects, I recommend starting with [cargo-pgo](https://github.com/Kobzol/cargo-pgo).

**Comment by agourlay** [comment]
This sounds interesting, thank you for raising this issue :+1: 

What do you miss or need to be able to try `cargo-pgo`?

**Comment by zamazan4ik** [comment]
> What do you miss or need to be able to try cargo-pgo?

I've created the issue as an idea to try PGO on Qdrant. Regarding applying PGO to Qdrant, if https://github.com/qdrant/qdrant/tree/master/benches benchmarks have good coverage from the Qdrant functionality perspective, I think we can try to test PGO on it.

The only thing I miss is free time to do it :) (since I am working on enabling PGO for multiple projects).

**Comment by zamazan4ik** [comment]
> I think it would help to prioritize this work to have a basic experiment demonstrating how much it costs to setup/maintain for which potential performance gain.

Well, if we are going to use benchmarks as a PGO training and evaluation set, I need to understand how to run the benchmarks with Qdrant. Are they integrated via `cargo bench`?

**Comment by zamazan4ik** [comment]
Well, at least `cargo bench` in the root `qdrant` repo runs nothing:
```
Finished bench [optimized] target(s) in 4m 43s
     Running unittests src/main.rs (target/release/deps/qdrant-e69b7ac971f11c78)

running 16 tests
test actix::api::collections_api::tests::timeout_is_deserialized ... ignored
test actix::api::read_params::test::deserialize_empty_string ... ignored
test actix::api::read_params::test::deserialize_empty_value ... ignored
test actix::api::read_params::test::deserialize_factor ... ignored
test actix::api::read_params::test::deserialize_type ... ignored
test actix::api::read_params::test::try_deserialize_factor_0 ... ignored
test actix::tests::test_version ... ignored
test common::helpers::tests::test_is_ready ... ignored
test common::metrics::tests::test_endpoint_whitelists_sorted ... ignored
test consensus::tests::collection_creation_passes_consensus ... ignored
test greeting::tests::test_welcome ... ignored
test settings::tests::test_custom_config ... ignored
test settings::tests::test_default_config ... ignored
test settings::tests::test_no_config_files ... ignored
test settings::tests::test_runtime_development_config ... ignored
test tonic::api::tests::test_validation ... ignored

test result: ok. 0 passed; 0 failed; 16 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

As far as I see in https://github.com/qdrant/qdrant/blob/master/benches/search-points/search-points.sh , the benchmarks should be run in a different way:
1. Compile and run Qdrant instance
2. Run `search-points.sh` script
3. Collect benchmark data

Maybe, I will try to do it a bit later :)

**Comment by agourlay** [comment]
Then `cargo criterion --all` should unleash the kraken :octopus:

**Comment by zamazan4ik** [comment]
> Then cargo criterion --all should unleash the kraken

Yeah, it definitely should :) The problem is that https://github.com/Kobzol/cargo-pgo relies on `cargo bench` integration. So if we want to build PGO-optimized Qdrant version, we need to do a little bit more work. It's of course possible to do (no rocket science at all) but just a little bit more work to do here.

**Comment by agourlay** [comment]
If you step into the lib crates, you can run benchmarks directly.

```bash
cd lib/segment
cargo bench --bench hnsw_build_graph
```

**Comment by zamazan4ik** [comment]
@agourlay During testing on Macbook M1 with macOS 13.4 (Ventura) and Qdrant from `master` branch (commit `0f102a5575ac33df03f06563844198f3ea26136b`) I get the following error:
```
cd lib/segment
RUST_BACKTRACE=1 cargo bench --bench hnsw_build_asymptotic
    Finished bench [optimized] target(s) in 0.24s
     Running benches/hnsw_build_asymptotic.rs (/Users/zamazan4ik/open_source/qdrant/target/release/deps/hnsw_build_asymptotic-215d8cb651e6cb54)
Gnuplot not found, using plotters backend
hnsw-index-build-asymptotic/build-n-search-hnsw
                        time:   [26.704 µs 26.792 µs 26.902 µs]
                        change: [-0.6981% -0.2924% +0.1105%] (p = 0.17 > 0.05)
                        No change in performance detected.
Found 9 outliers among 100 measurements (9.00%)
  3 (3.00%) high mild
  6 (6.00%) high severe
hnsw-index-build-asymptotic/build-n-search-hnsw-10x
                        time:   [31.965 µs 32.401 µs 32.844 µs]
                        change: [-1.5955% +0.5111% +2.6498%] (p = 0.64 > 0.05)
                        No change in performance detected.
hnsw-index-build-asymptotic/build-n-search-hnsw-10x-score-point
                        time:   [33.176 µs 33.408 µs 33.735 µs]
                        change: [-0.5501% +0.1561% +0.9129%] (p = 0.67 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe

Benchmarking scoring-vector/score-point: Warming up for 3.0000 sthread 'main' panicked at 'internal error: entered unreachable code: FakeMetric::distance', lib/segment/benches/hnsw_build_asymptotic.rs:113:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: <hnsw_build_asymptotic::FakeMetric as segment::spaces::metric::Metric>::distance
   3: segment::vector_storage::raw_scorer::raw_scorer_impl
   4: criterion::bencher::Bencher<M>::iter
   5: <criterion::routine::Function<M,F,T> as criterion::routine::Routine<M,T>>::warm_up
   6: criterion::routine::Routine::sample
   7: criterion::analysis::common
   8: criterion::benchmark_group::BenchmarkGroup<M>::bench_function
   9: hnsw_build_asymptotic::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: bench failed, to rerun pass `--bench hnsw_build_asymptotic`
```

**Comment by zamazan4ik** [comment]
I benchmarked `segment` with PGO on my Macbook M1 Pro, macOS Ventura 13.4. The background noise was the same. The only disabled benchmark is `hnsw_build_asymptotic ` since it doesn't work on the current Qdrant version on my machine (see the comment above about the panic).

The results are the following:
* Release: https://pastebin.com/cKtsaWn8
* PGO Instrumentation compared to Release: https://pastebin.com/crsEY7yH
* PGO Optimized compared to Release: https://pastebin.com/31TtmCky

According to these microbenchmarks, PGO helps with achieving better performance in almost all cases. However, would be much more interesting to test Qdrant itself with PGO.

Additionally, I want to highlight, that some used by Qdrant 3rd-parties could be optimized with PGO as well. For E.g. RocksDB as a C++ dependency will not be optimized with `cargo pgo` but RocksDB benefits from PGO too according to my tests (somewhere near 10% in performance).

**Comment by zamazan4ik** [comment]
I just finished Qdrant benchmarks with PGO and want to share my current results.

## Test environment

* Fedora 38
* Linux kernel 6.4.12
* AMD Ryzen 9 5800x
* 48 Gib RAM
* SSD Samsung 980 Pro 2 Tib
* Rust: 1.72
* Latest Qdrant from the `master` branch (commit `0f102a5575ac33df03f06563844198f3ea26136b `)

As a benchmark, I use gRPC Upsert and gRPC Search benchmarks from here: https://github.com/qdrant/qdrant/tree/master/benches/service . The PGO optimization is done with `cargo-pgo`. Between each run the Qdrant state on the disk was deleted.

## Results

### Release
Upsert:
```
upsert points status is OK

     █ setup

       ✓ delete collection status is OK
       ✓ create new collection status is OK
       ✓ add payload index status is OK

     checks...............: 100.00% ✓ 9378         ✗ 0   
     data_received........: 661 kB  78 kB/s
     data_sent............: 170 MB  20 MB/s
     grpc_req_duration....: avg=19.42ms min=435.99µs med=18.71ms max=625.38ms p(90)=22.8ms  p(95)=24.62ms
     iteration_duration...: avg=25.17ms min=7.62ms   med=24.16ms max=627.39ms p(90)=28.45ms p(95)=30.69ms
     iterations...........: 9375    1104.093135/s
     points_count.........: 300000  35330.980313/s
     vus..................: 30      min=30         max=30
     vus_max..............: 30      min=30         max=30


running (00m08.5s), 00/30 VUs, 9375 complete and 0 interrupted iterations
upsert_points ✓ [ 100% ] 30 VUs  00m07.9s/10m0s  9375/9375 shared iters
```
Search:
```
search_points status is 200

     checks...............: 100.00% ✓ 50088      ✗ 0   
     data_received........: 2.9 GB  48 MB/s
     data_sent............: 33 MB   548 kB/s
     grpc_req_duration....: avg=7.99ms  min=1.65ms med=6.57ms  max=47.38ms p(90)=15.12ms p(95)=18.53ms
     iteration_duration...: avg=17.95ms min=5.21ms med=16.54ms max=82.05ms p(90)=28ms    p(95)=31.66ms
     iterations...........: 50088   834.600824/s
     vus..................: 29      min=1        max=29
     vus_max..............: 30      min=30       max=30


running (1m00.0s), 00/30 VUs, 50088 complete and 0 interrupted iterations
search_points ✓ [ 100% ] 00/30 VUs  1m0s
```

### Release + PGO optimized
Upsert:
```
upsert points status is OK

     █ setup

       ✓ delete collection status is OK
       ✓ create new collection status is OK
       ✓ add payload index status is OK

     checks...............: 100.00% ✓ 9378         ✗ 0   
     data_received........: 661 kB  84 kB/s
     data_sent............: 170 MB  22 MB/s
     grpc_req_duration....: avg=17.12ms min=317.71µs med=16.53ms max=635.98ms p(90)=20.49ms p(95)=22.29ms
     iteration_duration...: avg=23.05ms min=6.26ms   med=22.05ms max=637.64ms p(90)=26.26ms p(95)=28.27ms
     iterations...........: 9375    1195.847456/s
     points_count.........: 300000  38267.118607/s
     vus..................: 30      min=30         max=30
     vus_max..............: 30      min=30         max=30


running (00m07.8s), 00/30 VUs, 9375 complete and 0 interrupted iterations
upsert_points ✓ [ 100% ] 30 VUs  00m07.2s/10m0s  9375/9375 shared iters
```
Search:
```
search_points status is 200

     checks...............: 100.00% ✓ 54341      ✗ 0   
     data_received........: 3.1 GB  52 MB/s
     data_sent............: 36 MB   594 kB/s
     grpc_req_duration....: avg=6.81ms  min=1.49ms med=5.69ms  max=44.41ms p(90)=12.58ms p(95)=15.76ms
     iteration_duration...: avg=16.55ms min=5.14ms med=15.35ms max=71.6ms  p(90)=25.4ms  p(95)=28.73ms
     iterations...........: 54341   905.492364/s
     vus..................: 29      min=1        max=29
     vus_max..............: 30      min=30       max=30


running (1m00.0s), 00/30 VUs, 54341 complete and 0 interrupted iterations
search_points ✓ [ 100% ] 00/30 VUs  1m0s
```
### Release + Instrumented
I put these numbers here so you can estimate how Qdrant is slow during the PGO instrumentation phase.

Upsert:
```
upsert points status is OK

     █ setup

       ✓ delete collection status is OK
       ✓ create new collection status is OK
       ✓ add payload index status is OK

     checks...............: 100.00% ✓ 9378         ✗ 0   
     data_received........: 661 kB  71 kB/s
     data_sent............: 170 MB  18 MB/s
     grpc_req_duration....: avg=22.16ms min=741.75µs med=21.44ms max=644.99ms p(90)=25.95ms p(95)=27.45ms
     iteration_duration...: avg=27.59ms min=5.25ms   med=26.51ms max=648.22ms p(90)=31.25ms p(95)=33.56ms
     iterations...........: 9375    1011.143339/s
     points_count.........: 300000  32356.586854/s
     vus..................: 30      min=30         max=30
     vus_max..............: 30      min=30         max=30


running (00m09.3s), 00/30 VUs, 9375 complete and 0 interrupted iterations
upsert_points ✓ [ 100% ] 30 VUs  00m08.6s/10m0s  9375/9375 shared iters
```
Search:
```
search_points status is 200

     checks...............: 100.00% ✓ 21118      ✗ 0   
     data_received........: 1.2 GB  20 MB/s
     data_sent............: 14 MB   231 kB/s
     grpc_req_duration....: avg=29.88ms min=3.62ms med=25.46ms max=182.58ms p(90)=53.49ms p(95)=61.74ms
     iteration_duration...: avg=42.64ms min=7.11ms med=38.62ms max=212.39ms p(90)=73.33ms p(95)=84.13ms
     iterations...........: 21118   351.735717/s
     vus..................: 29      min=1        max=29
     vus_max..............: 30      min=30       max=30


running (1m00.0s), 00/30 VUs, 21118 complete and 0 interrupted iterations
search_points ✓ [ 100% ] 00/30 VUs  1m0s
```

## Conclusion

PGO helps to achieve better performance with Qdrant according to the benchmarks above. I think it would be a good idea to put information about building Qdrant with PGO into the documentation.

**Comment by agourlay** [comment]
Thanks for the deep investigation :+1: 

FYI we have finally fixed the panic in the `hnsw_build_asymptotic` bench :)
