### ISSUE TITLE
Bad Request: Format error in JSON body: data did not match any variant of untagged enum VectorStruct

### ISSUE THREAD

**Issue by bencmbrook** [qdrant/qdrant#2424]
When calling `this.client.upsert()` I'm consistently getting an error **Format error in JSON body: data did not match any variant of untagged enum VectorStruct at line 1 column 18662735**.

Getting this stack trace:

```
ApiError: Bad Request
    at Object.fun ({{myproject}}/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:150:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at QdrantClient.upsert ({{myproject}}/node_modules/@qdrant/js-client-rest/dist/cjs/qdrant-client.js:488:26)
    at QdrantVectorStore.addVectors ({{myproject}}/lib/ai/qdrant/QdrantVectorStore.ts:109:7)
```

And where `addVectors` is calling:

```ts
await this.client.upsert(this.collectionName, {
    wait: true,
    points: safePointsSlice, // of type number[]
});
```

**Comment by bencmbrook** [comment]
This error was occurring due to `points[i].vector` being occasionally `null`. Closing this since it's not a bug, but a better error message would be great!

**Comment by timvisee** [comment]
Good to see you found the culprit.

I agree that improving the error message for this would be great. I'm afraid we can't (easily) do that though, since this is an internal deserialization error, so our validation logic isn't even reached.
