### ISSUE TITLE
Replica of shard  has state error

### ISSUE THREAD

**Issue by chenbt-hz** [qdrant/qdrant#2465]
Benchmark program often experiences irregular errors and stops running.
By the way, just to let you know, under the same conditions, I obtained performance metrics that were twice as good in a load test conducted one week ago. I am unsure if this issue is related, though.

## Current Behavior

vector-db-benchmark no error
## Steps to Reproduce

**1.cd vector-db-benchmark** 
 **2.python3 run.py  --engines qdrant-\*  --datasets gist-\*  --host $hostip --no-skip-upload  --no-skip-search** 
**3. Error logs:**
AnnH5Reader read_queries finished.

8it [00:00, 611.09it/s]
Traceback (most recent call last):
  File "run.py", line 58, in run
    client.run_experiment(dataset, skip_upload, skip_search)
  File "/app/qdrant_vectordb_benchmark/vector-db-benchmark-master/engine/base_client/client.py", line 88, in run_experiment
    search_stats = searcher.search_all(
  File "/app/qdrant_vectordb_benchmark/vector-db-benchmark-master/engine/base_client/search.py", line 102, in search_all
    zip(*pool.imap_unordered(search_one, iterable=tqdm.tqdm(queries)))
  File "/usr/local/python3/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7faa182d6670>'. Reason: 'TypeError("cannot pickle '_thread.RLock' object")'
AnnH5Reader read_queries
Experiment qdrant-m-16-ef-128 - gist-960-euclidean interrupted
Traceback (most recent call last):

  File "run.py", line 85, in <module>
    app()

  File "run.py", line 80, in run
    raise e

  File "run.py", line 58, in run
    client.run_experiment(dataset, skip_upload, skip_search)

  File "/app/qdrant_vectordb_benchmark/vector-db-benchmark-master/engine/base_client/client.py", line 88, in run_experiment
    search_stats = searcher.search_all(

  File "/app/qdrant_vectordb_benchmark/vector-db-benchmark-master/engine/base_client/search.py", line 102, in search_all
    zip(*pool.imap_unordered(search_one, iterable=tqdm.tqdm(queries)))

  File "/usr/local/python3/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value

multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7faa182d6670>'. Reason: 'TypeError("cannot pickle '_thread.RLock' object")'

**4.kubectl logs -f --tail=5  test-qdrant-1**
[2023-08-18T01:41:14.436Z WARN  storage::content_manager::consensus_manager] Failed to apply collection meta operation entry with user error: Wrong input: Replica 7025067289929045 of shard 2 has state Some(Active), but expected Some(Initializing)
[2023-08-18T01:41:14.891Z WARN  storage::content_manager::consensus_manager] Failed to apply collection meta operation entry with user error: Wrong input: Replica 4259549066635120 of shard 0 has state Some(Active), but expected Some(Initializing)

### uname -a
Linux master 5.4.251-1.el7.elrepo.x86_64 #1 SMP Thu Jul 27 18:49:53 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
### cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)

**Comment by mayank2130** [comment]
If you need to share data between processes, use mechanisms such as multiprocessing.Queue, multiprocessing.Manager.
Also, avoid sharing non-picklable objects.
