### ISSUE TITLE
batch update points fails to complete and leaves collection in unrecoverable state

### ISSUE THREAD

**Issue by tekumara** [qdrant/qdrant#2751]
[batch_update_points](https://github.com/tekumara/qdrant-demo/blob/683e74c867318a38c36371331603b65d74c05b85/demo/batch_update.py#L70) with write ordering STRONG fails to complete and leaves collection in unrecoverable state.

## Current Behavior

When making the following request via the python client using GRPC:
```python
   qdrant_client.batch_update_points(
        collection_name=COLLECTION_NAME,
        update_operations=ops,
        wait=False,
        ordering=types.WriteOrdering.STRONG,
    )
```
The request blocks and doesn't return. A keyboard interrupt is required to terminate the request. 

After termination scroll returns:

```
Service internal error: The replica set for shard 1 on peer 463081048243523 does not have enough active replicas
```

Server logs:

```
qdrant-1 qdrant 2023-09-30T10:31:01.445755Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 873440205739692 of shard 1    
qdrant-0 qdrant 2023-09-30T10:31:01.450013Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 463081048243523 of shard 0    
qdrant-1 qdrant 2023-09-30T10:31:01.452742Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 463081048243523 of shard 0    
qdrant-2 qdrant 2023-09-30T10:31:01.452902Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 463081048243523 of shard 0    
qdrant-0 qdrant 2023-09-30T10:31:01.487451Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 873440205739692 of shard 1    
qdrant-1 qdrant 2023-09-30T10:31:01.489867Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 873440205739692 of shard 1    
qdrant-2 qdrant 2023-09-30T10:31:01.490222Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 873440205739692 of shard 1    
qdrant-0 qdrant 2023-09-30T10:31:01.494224Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 3328066235175196 of shard 2    
qdrant-2 qdrant 2023-09-30T10:31:01.496200Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 3328066235175196 of shard 2    
qdrant-1 qdrant 2023-09-30T10:31:01.496276Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Wrong input: Cannot deactivate the last active replica 3328066235175196 of shard 2
```

## Steps to Reproduce

Create cluster using `make kubes` from [tekumara/qdrant-demo](https://github.com/tekumara/qdrant-demo)

Run [demo.batch_update](https://github.com/tekumara/qdrant-demo/blob/683e74c867318a38c36371331603b65d74c05b85/demo/batch_update.py). It fails to complete so press ^C to abort:

```
❯ python -m demo.batch_update
recreate_collection
batch_update_points
^CTraceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tekumara/code/qdrant-demo/demo/race.py", line 84, in <module>
    main()
  File "/Users/tekumara/code/qdrant-demo/demo/race.py", line 70, in main
    qdrant_client.batch_update_points(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1185, in batch_update_points
    return self._client.batch_update_points(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 1501, in batch_update_points
    for result in self.grpc_points.UpdateBatch(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 1158, in __call__
    ) = self._blocking(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 1142, in _blocking
    event = call.next_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 366, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 187, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 181, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 78, in grpc._cython.cygrpc._latent_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 61, in grpc._cython.cygrpc._internal_latent_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 42, in grpc._cython.cygrpc._next
KeyboardInterrupt
```

Scroll:
```
❯ curl 'http://localhost:6333/collections/birds/points/scroll' -H 'content-type: application/json' --data-raw '{"limit":10,"offset":null,"with_payload":true,"with_vector":true}'
{"status":{"error":"Service internal error: The replica set for shard 0 on peer 873440205739692 does not have enough active replicas"},"time":0.001493125}
```

## Possible Solution

Deleting the collection is the only way I've found to recover from this state.

## Context (Environment)

qdrant 1.5.1 across 3 replicas deployed to kubernetes 

qdrant-client==1.5.4 (python) using grpc

**Comment by tekumara** [comment]
Also replicates with `types.WriteOrdering.MEDIUM` but not `types.WriteOrdering.WEAK`.

**Comment by tekumara** [comment]
Also replicates with `types.WriteOrdering.MEDIUM` but not `types.WriteOrdering.WEAK`. Perhaps there's a deadlock somewhere ..

**Comment by generall** [comment]
Hi @tekumara, thanks a lot for reporting this issue.

I can confirm that I was able to reproduce the problem using your script.

We will prepare a fix ASAP

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/qdrant/releases/tag/v1.6.0
