### ISSUE TITLE
Error when gRPC search batch points does not specify a collection name for each search

### ISSUE THREAD

**Issue by russcam** [qdrant/qdrant#2880]
Qdrant version: v1.6.1, docker container running on WSL

When attempting to call the search batch points API over gRPC with a client generated from the protos, an internal error occurs when
each search points in the batch does not specify a collection name. The error occurs here with a [C# client](https://github.com/russcam/qdrant-dotnet-client), but from memory, the same issue also occurs with a [Java client](https://github.com/metaloom/qdrant-java-client).

## Current Behavior

An error occurs with the following panic backtrace

```
2023-10-26 22:35:21 2023-10-26T12:35:21.637303Z ERROR qdrant::startup: Panic backtrace: 
2023-10-26 22:35:21    0: qdrant::startup::setup_panic_hook::{{closure}}
2023-10-26 22:35:21    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
2023-10-26 22:35:21              at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
2023-10-26 22:35:21    2: std::panicking::rust_panic_with_hook
2023-10-26 22:35:21              at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
2023-10-26 22:35:21    3: std::panicking::begin_panic::{{closure}}
2023-10-26 22:35:21    4: std::sys_common::backtrace::__rust_end_short_backtrace
2023-10-26 22:35:21    5: std::panicking::begin_panic
2023-10-26 22:35:21    6: validator::types::ValidationErrors::merge
2023-10-26 22:35:21    7: <alloc::vec::Vec<V> as api::grpc::validate::ValidateExt>::validate
2023-10-26 22:35:21    8: <qdrant::tonic::api::points_api::PointsService as api::grpc::qdrant::points_server::Points>::search_batch::{{closure}}
2023-10-26 22:35:21    9: <<api::grpc::qdrant::points_server::PointsServer<T> as tower_service::Service<http::request::Request<B>>>::call::SearchBatchSvc<T> as tonic::server::service::UnaryService<api::grpc::qdrant::SearchBatchPoints>>::call::{{closure}}
2023-10-26 22:35:21   10: <api::grpc::qdrant::points_server::PointsServer<T> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
2023-10-26 22:35:21   11: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
2023-10-26 22:35:21   12: <tonic::transport::service::router::RoutesFuture as core::future::future::Future>::poll
2023-10-26 22:35:21   13: <qdrant::tonic::tonic_telemetry::TonicTelemetryService<S> as tower_service::Service<http::request::Request<hyper::body::body::Body>>>::call::{{closure}}
2023-10-26 22:35:21   14: <qdrant::tonic::logging::LoggingMiddleware<S> as tower_service::Service<http::request::Request<hyper::body::body::Body>>>::call::{{closure}}
2023-10-26 22:35:21   15: <tonic::transport::server::SvcFuture<F> as core::future::future::Future>::poll
2023-10-26 22:35:21   16: <hyper::proto::h2::server::H2Stream<F,B> as core::future::future::Future>::poll
2023-10-26 22:35:21   17: tokio::runtime::task::raw::poll
2023-10-26 22:35:21   18: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
2023-10-26 22:35:21   19: tokio::runtime::task::raw::poll
2023-10-26 22:35:21   20: std::sys_common::backtrace::__rust_begin_short_backtrace
2023-10-26 22:35:21   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
2023-10-26 22:35:21   22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2023-10-26 22:35:21              at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
2023-10-26 22:35:21   23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2023-10-26 22:35:21              at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
2023-10-26 22:35:21   24: std::sys::unix::thread::Thread::new::thread_start
2023-10-26 22:35:21              at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys/unix/thread.rs:108:17
2023-10-26 22:35:21   25: <unknown>
2023-10-26 22:35:21   26: clone
2023-10-26 22:35:21     
2023-10-26 22:35:21 2023-10-26T12:35:21.637337Z ERROR qdrant::startup: Panic occurred in file /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/validator-0.16.1/src/types.rs at line 156: Attempt to replace non-empty ValidationErrors entry
```

## Steps to Reproduce

A repro test can be found at https://github.com/russcam/qdrant-dotnet-client/blob/b39a61b0a59a2b5bbb236276e194646c45bb7476/tests/Qdrant.Grpc.Tests/PointsTests.cs#L13-L57.

When executing the test as is, an exception is thrown with the following stack trace 

```
Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. HttpProtocolException: The HTTP/2 server reset the stream. HTTP/2 error code 'CANCEL' (0x8).", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.")
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.HttpProtocolException: The HTTP/2 server reset the stream. HTTP/2 error code 'CANCEL' (0x8).
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   --- End of inner exception stack trace ---
   at Qdrant.Grpc.Tests.PointsTests.SearchBatch() in C:\Users\russc\source\QdrantNet\tests\Qdrant.Grpc.Tests\PointsTests.cs:line 23
```

If the `CollectionName` is specified for each `SearchPoints`, there is no error. 

## Expected Behavior

It seems like it should be possible to specify `CollectionName` once, on the top level property of the `SearchBatchPoints` request, and this be taken as the collection name for all `SearchPoints` items. The [Open API spec](https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/search_batch_points) _implies_ this is the case for JSON, with collection_name specified in the path.

## Possible Solution

It looks to me like it _may_ be a bug, and a consequence of the [validation on `SearchPoints` for collection name](https://github.com/qdrant/qdrant/blob/b15d290a3ab1b8e02f2ca6132dbcdd8f47444db8/lib/api/src/grpc/qdrant.rs#L3070-L3071) invoked when validating [`SearchBatchPoints`](https://github.com/qdrant/qdrant/blob/b15d290a3ab1b8e02f2ca6132dbcdd8f47444db8/lib/api/src/grpc/qdrant.rs#L3116-L3117).

The error also happens for a similar reason on recommend batch points; validation on [collection name of `RecommendPoints`](https://github.com/qdrant/qdrant/blob/b15d290a3ab1b8e02f2ca6132dbcdd8f47444db8/lib/api/src/grpc/qdrant.rs#L3232-L3233) when validating [`RecommendBatchPoints`](https://github.com/qdrant/qdrant/blob/b15d290a3ab1b8e02f2ca6132dbcdd8f47444db8/lib/api/src/grpc/qdrant.rs#L3282-L3283). 

## Workaround

The workaround for now is to specify the collection name on every item.

**Comment by generall** [comment]
@russcam thanks for reporting, reproduced the problem here: https://github.com/qdrant/qdrant/pull/2888

**Comment by timvisee** [comment]
@russcam Thank you for the report! This has been fixed in <https://github.com/qdrant/qdrant/pull/2888>, which will be part of the next release.
