### ISSUE TITLE
Dependabot does not run anymore

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#2985]
Dependabot does not like our new virtual common crate setup. 

It seems it did not run since its addition.

Checking the logs we clearly see

```
(Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/11/13 11:02:44 ERROR <job_749006256> error: failed to load manifest for workspace member `dependabot_tmp_dir/lib/common/src`
updater | 
updater | Caused by:
updater |   failed to read `dependabot_tmp_dir/lib/common/src/Cargo.toml`
updater | 
updater | Caused by:

```

Full logs of https://github.com/qdrant/qdrant/security/dependabot/56/update-logs/353253170

```
  proxy | 2023/11/13 11:02:26 proxy starting, commit: 720801aa060f51bd9dc8b5753a6045ec3d7f5321
  proxy | 2023/11/13 11:02:26 Listening (:1080)
updater | 2023-11-13T11:02:26.445706281 [749006256:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-11-13T11:02:28Z" level=info msg="guest starting" commit=480200678d7877c9eb94d16566d7ee0d2e75c9bf
updater | time="2023-11-13T11:02:28Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=749006256 updater_timeout=45m0s updater_version=6c4675c7d545ba1a23b0b2b10991e7793a3015f8-cargo
updater | 2023/11/13 11:02:29 INFO Raven 3.1.2 ready to catch errors
updater | 2023/11/13 11:02:30 INFO <job_749006256> Starting job processing
  proxy | 2023/11/13 11:02:31 [002] GET https://api.github.com:443/repos/qdrant/qdrant
  proxy | 2023/11/13 11:02:31 [002] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:31 [002] 200 https://api.github.com:443/repos/qdrant/qdrant
  proxy | 2023/11/13 11:02:31 [004] GET https://api.github.com:443/repos/qdrant/qdrant/git/refs/heads/master
  proxy | 2023/11/13 11:02:31 [004] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:31 [004] 200 https://api.github.com:443/repos/qdrant/qdrant/git/refs/heads/master
  proxy | 2023/11/13 11:02:31 [006] GET https://api.github.com:443/repos/qdrant/qdrant/contents/?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:31 [006] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:31 [006] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:32 [010] GET https://api.github.com:443/repos/qdrant/qdrant/contents/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:32 [010] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:32 [010] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:32 [012] GET https://api.github.com:443/repos/qdrant/qdrant/contents/Cargo.lock?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:32 [012] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:32 [012] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/Cargo.lock?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:32 [014] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/common/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:32 [014] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:32 [014] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/common/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [016] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/memory/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [016] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:33 [016] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/memory/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [018] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/segment/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [018] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:33 [018] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/segment/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [020] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/io/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [020] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:33 [020] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/io/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [022] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/sparse/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [022] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:33 [022] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/sparse/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [024] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/collection/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:33 [024] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:34 [024] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/collection/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:34 [026] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/api/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:34 [026] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:34 [026] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/api/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:34 [028] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/storage/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:34 [028] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:34 [028] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/storage/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:35 [030] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:35 [030] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:35 [030] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:35 [032] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:35 [032] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:35 [032] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:35 [034] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/api/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:35 [034] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:35 [034] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/api/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:35 [036] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/collection/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:35 [036] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:35 [036] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/collection/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [038] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [038] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:36 [038] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [040] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/segment/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [040] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:36 [040] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/segment/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [042] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/sparse/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [042] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:36 [042] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/sparse/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [044] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/storage/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [044] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:36 [044] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/storage/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [046] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/common/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [046] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:36 [046] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/common/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [048] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/io/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [048] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:36 [048] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/io/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [050] GET https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/memory/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
  proxy | 2023/11/13 11:02:36 [050] * authenticating github api request with token for api.github.com
  proxy | 2023/11/13 11:02:37 [050] 200 https://api.github.com:443/repos/qdrant/qdrant/contents/lib/common/memory/Cargo.toml?ref=e686e71b9f514e9f8723c29591003f87b495ae87
updater | 2023/11/13 11:02:38 INFO <job_749006256> Finished job processing
updater | time="2023-11-13T11:02:38Z" level=info msg="task complete" container_id=job-749006256-file-fetcher exit_code=0 job_id=749006256 step=fetcher
updater | 2023/11/13 11:02:39 INFO Raven 3.1.2 ready to catch errors
updater | 2023/11/13 11:02:40 INFO <job_749006256> Starting job processing
updater | 2023/11/13 11:02:42 INFO <job_749006256> Starting security update job for qdrant/qdrant
updater | 2023/11/13 11:02:42 INFO <job_749006256> Checking if rustix 0.35.13 needs updating
  proxy | 2023/11/13 11:02:42 [056] GET https://crates.io:443/api/v1/crates/rustix
  proxy | 2023/11/13 11:02:42 [056] 200 https://crates.io:443/api/v1/crates/rustix
updater | 2023/11/13 11:02:42 INFO <job_749006256> Latest version is 0.38.21
updater | 2023/11/13 11:02:44 INFO <job_749006256> Sending event 2d281b0488c14c94bdd677d3f553eb87 to Sentry
  proxy | 2023/11/13 11:02:44 [058] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/11/13 11:02:44 [058] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/11/13 11:02:44 ERROR <job_749006256> Error processing rustix (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/11/13 11:02:44 ERROR <job_749006256> error: failed to load manifest for workspace member `dependabot_tmp_dir/lib/common/src`
updater | 
updater | Caused by:
updater |   failed to read `dependabot_tmp_dir/lib/common/src/Cargo.toml`
updater | 
updater | Caused by:
updater |   No such file or directory (os error 2)
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:153:in `run_cargo_command'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:137:in `run_cargo_update_command'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:47:in `block (2 levels) in fetch_latest_resolvable_version'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/shared_helpers.rb:264:in `with_git_configured'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:46:in `block in fetch_latest_resolvable_version'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/shared_helpers.rb:80:in `block in in_a_temporary_directory'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/shared_helpers.rb:80:in `chdir'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/shared_helpers.rb:80:in `in_a_temporary_directory'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:43:in `fetch_latest_resolvable_version'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:33:in `latest_resolvable_version'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/cargo/lib/dependabot/cargo/update_checker.rb:241:in `fetch_lowest_resolvable_security_fix_version'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/cargo/lib/dependabot/cargo/update_checker.rb:56:in `lowest_resolvable_security_fix_version'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:266:in `preferred_version_resolvable_with_unlock?'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:258:in `numeric_version_can_update?'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:208:in `version_can_update?'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:46:in `can_update?'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:233:in `requirements_to_unlock'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/
create_security_update_pull_request.rb:113:in `check_and_create_pull_request'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:64:in `check_and_create_pr_with_error_handling'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `block in perform'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `each'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `perform'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/13 11:02:44 ERROR <job_749006256> bin/update_files.rb:24:in `<main>'
updater | 2023/11/13 11:02:44 INFO <job_749006256> Finished job processing
updater | 2023/11/13 11:02:44 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | | Dependencies failed to update |
updater | +---------------+---------------+
updater | | rustix        | unknown_error |
updater | +---------------+---------------+
updater | time="2023-11-13T11:02:44Z" level=info msg="task complete" container_id=job-749006256-updater exit_code=0 job_id=749006256 step=updater
Footer


```

**Comment by timvisee** [comment]
Fixed in <https://github.com/qdrant/qdrant/pull/2986>.
