### ISSUE TITLE
Timeout on collection deletion

### ISSUE THREAD

**Issue by homier** [qdrant/qdrant#3121]
Hey guys!

### HTTP deletion with default timeout
```bash
curl -X DELETE 127.0.0.1:6333/collections/collection-to-be-deleted

{"status":{"error":"Service internal error: Waiting for consensus operation commit failed. Timeout set at: 10 seconds"},"time":10.001176907}
```

### gRPC deletion with timeout set to 100 seconds
```bash
grpcurl -plaintext -d '{"timeout": 100, "collection_name": "collection-to-be-deleted"}' 127.0.0.1:6334 qdrant.Collections/Delete
ERROR:
  Code: Internal
  Message: Service internal error: Waiting for consensus operation commit failed. Timeout set at: 100 seconds
```

I'll describe how we create those collection in steps to reproduce.

## Steps to Reproduce

1.  Create a collection using gRPC: 
```bash
grpcurl -plaintext \
  -d '{"collection_name": "delete-me", "hnsw_config": {"m": 16, "ef_construct": 100}, "optimizers_config": {"indexing_threshold": 100000}, "replication_factor": 2, "write_consistency_factor": 2, "vectors_config": {"params": {"size": 512, "distance": "Cosine"}}}'  \
  localhost:6334 qdrant.Collections/Create 
```
2. Create two integer indexes (foo, bar):
```bash
grpcurl -plaintext \
  -d '{"collection_name": "delete-me", "field_name": "foo", "field_type": 1, "wait": true}' \
  localhost:6334 qdrant.Points/CreateFieldIndex
```
3. Fill the collection with a some (415 in our case) bunch of points like in the following example:
```bash
grpcurl -plaintext \
  -d '{"collection_name": "delete-me", "points": [{"id": {"uuid": "400c9f7e-37c6-451d-b600-50cfcc9876fa"}, "vectors": {"vector": {"data": []}}, "payload": {"foo": {"integer_value": 1}, "bar": {"integer_value": 2}}}],  "wait": true}' \
   localhost:6334 qdrant.Points/Upsert
```

Keep in mind, that I dropped the vector content since its too big to attach as an example, and the pa
4. Try to delete a collection with default timeout:
```bash
grpcurl -plaintext -d '{"collection_name": "delete-me"}' localhost:6334 qdrant.Collections/Delete
```
5. In case of timeout, increase it by passing it to the request body:
```bash
grpcurl -plaintext -d '{"collection_name": "delete-me", "timeout": 100}' localhost:6334 qdrant.Collections/Delete
```

## Expected Behav
Collection deletion should not stuck on time outs.

## Context (Environment)
1. qdrant version: v1.6.1 
2. 3 qdrant nodes in the same network, deployed on VMs
3. Logs from qdrant during timeouts:
```
ERROR qdrant::tonic::logging: gRPC /qdrant.Collections/Delete unexpectedly failed with Internal error "Service internal error: Waiting for consensus operation commit failed. Timeout set at: 30 seconds"
```
4. This issue happens only on one of the our environments
5. A log that is produced by Qdrant appears in the following method -  https://github.com/qdrant/qdrant/blob/5c36256caf94f7a90e31248415fd643818a09543/lib/storage/src/content_manager/toc/mod.rs#L533 , though it seems like this method is not used by any other part of the source code according to GitHub search.

## Detailed Description
We've started to see an issue with deleting collections from both HTTP and gRPC methods invoking.
Qdrant server cannot execute delete operation within default (10 seconds) timeout, and even when we set it to high value (for instance, 100 seconds) the issue is not gone.

Our qdrant cluster consists of 3 nodes  deployed on VMs, and all of them are located in the same network.

The collection we trying to delete (there are several of them, to be honest) has only 415 points and it's not used by clients anymore - no upsert/search operations on it.

I understand that the issue is quite difficult to reproduce, but it'd be nice if we could get some help with resolving it :)

**Comment by zafercavdar** [comment]
I experience the same issue and opened a ticket [here](https://github.com/qdrant/qdrant-helm/issues/100)

The search works as expected but `recreate_collection` method in Python client, which triggers DELETE first doesn't work.

**Comment by homier** [comment]
@zafercavdar your issue is quite similar to ours, though we don't have neither a log nor an issue related to cluster leader. I think we should wait until dev team joins :)

BTW, have you run any check on cluster health? It might be the key for you

**Comment by homier** [comment]
@timvisee
Hi!
Is there any chance the team could take a look into the issue? We are kind of stuck in this.

Apologize for tagging you if it is rude.

**Comment by mautini** [comment]
I experience the same issues since 2 days on two clusters (two and three nodes). It timeout during `recreate_collection` call (it seems that the delete work but the collection is then not recreated. 

What is strange is that I didn't change anything in the cluster (still running 1.6.0). Temporary fix is to restart each pod in the cluster.

Thanks,

**Comment by homier** [comment]
@lamboneko thanks for the tip! We've upgraded our cluster to the newest released version, hope the issue is gone now.
We'll be monitoring the situation and if everything is alright, I'll close the issue

**Comment by timvisee** [comment]
I've been trying to reproduce this for a bit, but didn't manage to do that yet.

On the machines on which this happens, do you possibly have slow disks and/or a lot of other IO operations happening at the same time? The issue just seems to be "deleting a collection takes too long", but it's not clear to me yet why.

**Comment by timvisee** [comment]
I've tried this for two more days without any luck. I cannot find a way to reproduce this, making it extremely hard to properly fix.

I did find another issue that may be related though, which I've fixed in <https://github.com/qdrant/qdrant/pull/3261>. It would be awesome if one of you can give it a spin to see if it may resolve things.

**Comment by nrakover** [comment]
Thank you @timvisee 🙏 Any ETA on when #3261 will land and get deployed? We've been experiencing severe instability on our cluster due to the consensus timeout, where the only known workaround is to cycle our Qdrant pods.

**Comment by timvisee** [comment]
> Thank you @timvisee 🙏 Any ETA on when #3261 will land and get deployed? We've been experiencing severe instability on our cluster due to the consensus timeout, where the only known workaround is to cycle our Qdrant pods.

No estimate, as I'm unsure if it is actually related to this issue. It would be awesome if someone can give it a spin evaluating whether it fixes, since I cannot reproduce the actual error myself.

**Comment by nrakover** [comment]
I don't have a deterministic repro unfortunately. We're running a single replica Qdrant deployment as part of our infra, and about once a week it suffers an unrecoverable failure.

The symptoms certainly line up with a race condition.

**Comment by mautini** [comment]
Hi Tim, FYI I didn't encounter the issue again...  At the same time, I upgraded to 1.7.0, so either it's a very rare issue or the update fixed the thing...

**Comment by nrakover** [comment]
I'm on v1.7.2 and have encountered the timeout at least once, unfortunately 😞

**Comment by timvisee** [comment]
It likely is very rare. If the issue is related to this race condition it'll only happen if the very same operation is sent at least twice in a very short period or time.

By the way, testing <https://github.com/qdrant/qdrant/pull/3261> will require compiling from scratch as described [here](https://github.com/qdrant/qdrant/blob/master/docs/DEVELOPMENT.md#build-qdrant).

**Comment by homier** [comment]
Hi folks!

@timvisee Sorry for the late answer, I wasn't checking notifications.

We haven't encountered the issue since we upgraded our cluster to v1.7.1, but I guess we are just lucky.
Will be waiting for the #3261 to be released, I hope this will fix the issue.

BTW, `if the very same operation is sent at least twice in a very short period or time.` - probably this is what happens. Briefly saying, we wipe collections that were created before some date threshold (for instance, a week ago). And the delete request itself could be potentially executed from two different services at the same time.

Thanks

**Comment by mautini** [comment]
Hello,

Unfortunately I got the error again today with Qdrant 1.7.2... But this time it happened during creation of an index on a payload field... 

My task is doing the following things : 
- Recreate the collection (empty)
- Fill it with ~700k points, each point has a payload
- Add indices on all fields in my payload (they are all used for filtering) <-- That's were it failed

I tried to add a wait after the insertion to be sure that my collection is green before the creation of the aliases, I hope it will help...

**Comment by generall** [comment]
Hi @mautini, we usually recommend to create payload indexes before uploading the data. It is expected that creating the index on existing collection is a long-running operation and it can timeout, especially if you run it with `wait=true`.

**Comment by mautini** [comment]
Oh thanks a lot, I didn't know it was possible to create the indices before. I'll change my job

**Comment by timvisee** [comment]
I took a few more days to extensively test this, but I cannot reproduce this at all with what is provided above. I did try many setups and scenarios, but no luck. 

Based on the error message

```
{"status":{"error":"Service internal error: Waiting for consensus operation commit failed. Timeout set at: 10 seconds"},"time":10.001176907}
```

the reason could very well be that some consensus operation could not be completed in time. 

To be more specific, creating a collection is relatively expensive because it needs to create a bunch of files on disk. Is it possible that the hardware you're running this on has slow disks? Or, that a lot of other disk operations are going on at the same time (such as large collection deletions) causing the disk to be busy?

Could you maybe elaborate on what kind of disk you're using? Also, would you mind to do a benchmark of them to measure the IOPS it can reach?

I did come across a different issue though. When you create a collection, it may not be ready on all nodes once the create call returns. So if you'd start upserting points right after, these may fail until the collection is fully ready.

To fix the above I've opened two more PRs (<https://github.com/qdrant/qdrant/pull/3318>, <https://github.com/qdrant/qdrant/pull/3329>). They aren't for your original issue, but they may improve the situation around it. I've also closed the PR I mentioned before (<https://github.com/qdrant/qdrant/pull/3261>) because it did not appear to have any effect in the end.

**Comment by timvisee** [comment]
Qdrant [1.7.4](https://github.com/qdrant/qdrant/releases/tag/v1.7.4) has just been released, which may improve the situation around this.

**Comment by homier** [comment]
@timvisee thanks for the release! We're upgrading our cluster to 1.7.4, if anything goes wrong we'll post a report in this issue

**Comment by timvisee** [comment]
That would be very much appreciated!

I'm afraid merging <https://github.com/qdrant/qdrant/pull/3329> may also be important here, but I still wanted to keep you all up to date anyway.

**Comment by Apidcloud** [comment]
I noticed https://github.com/qdrant/qdrant/pull/3329 was closed. Isn't it needed anymore or should we wait?

**Comment by timvisee** [comment]
> I noticed #3329 was closed. Isn't it needed anymore or should we wait?

Good that you mention it. Should not be needed anymore for this. It did improve internals but I didn't find any real case where the problem it solves could appear in our current code base. Since that change will be obsolete in some time we closed it now.

Has anyone of you seen this issue since 1.7.4?

**Comment by mautini** [comment]
No issue on my side since 1.7.4

**Comment by sigridjineth** [comment]
Hello, there's an issue on my side since 1.8.1 which was not a problem in 1.7.4

**Comment by lukywong** [comment]
@mautini same, i meet the issue on v1.9.2 inserting 26k points

**Comment by pasindu-pr** [comment]
> So I think that timeout during creating index is not related to original issue

@mautini  Did you find a solution to this?, I'm experiencing the same issue

**Comment by mautini** [comment]
No, I didn't get the issue since 1.7.4

**Comment by fvicaria** [comment]
Not sure if this is related so I decided to mention it here first instead of opening a new issue: 

```
ERROR qdrant::tonic::logging: gRPC /qdrant.Collections/Delete unexpectedly failed with Internal error Service internal error: Access is denied. (os error 5)
```

I get this when I try to delete a collection using the C# API. 
The collection disappears from the dashboard but it is still in the storage directory.

The call in C# fails but with exception also:
 
'''
await qdrantClient.DeleteCollectionAsync(collectionName, TimeSpan.FromSeconds(2));
'''

Get this:
'''
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Service internal error: Access is denied. (os error 5)")
   at Qdrant.Client.QdrantClient.DeleteCollectionAsync(String collectionName, Nullable`1 timeout, CancellationToken cancellationToken)
   at CultiFood.Vectorize.Program.DeleteCollectionIfExists(QdrantClient qdrantClient, String collectionName, String storagePath) in E:\CultiFood\CultiFood.Vectorize\Program.cs:line 121
   at CultiFood.Vectorize.Program.Main() in E:\CultiFood\CultiFood.Vectorize\Program.cs:line 43
   at CultiFood.Vectorize.Program.<Main>()
'''

I am running both, qdrant and the C# app as admin and there should be no reason it could not get rid of the collection.
I am forced to delete the directory also within the application as a workaround for the moment.

Any ideas?

**Comment by timvisee** [comment]
@fvicaria Your error shows `Access is denied. (os error 5)`, and therefore I don't think it's related.

It may be cause by misconfigured storage, where file permissions are not set up properly.
