### ISSUE TITLE
WAL might be too big

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#317]
Currently, WAL is truncated by the smallest SeqNumber of the segments. But if some indexed segment was not updated long enough - the difference between actual updates and the smallest version might be too high.

## Steps to Reproduce

1. Create a collection with default config and 100000 vectors
2. Observe ~10 WAL files

## Expected Behavior
No more than 3 files.

## Possible Solution
Change truncation logic

**Comment by e-ivkov** [comment]
So the idea is to truncate not by the smallest SeqNumber, but by avg/largest or some other measure? I am not sure, will the segments eventually synchronize the updates between themselves even without WAL, if some segment has these updates, right?

**Comment by e-ivkov** [comment]
I checked at https://github.com/qdrant/qdrant/commit/3b62670a1a18488d2a26363aae0e441602951fcf 

With latest benchmark: https://github.com/qdrant/benchmark/pull/3/files

Corrected the code to only have 100_000 vectors:
```python
self.client.upload_collection(
            collection_name=self.collection_name,
            vectors=self.data['train'][:100000],
            payload=None,
            ids=None,
            parallel=parallel
        )
```

Only 3 files are produced in wal folder: `closed-0  open-2  open-3`

These files also remain even after some time has passed after insertion and hnsw indexes were built - is this an intended behavior?

**Comment by e-ivkov** [comment]
On 1M `upload_data` script crashes with (but seems that only after it uploaded all the data):
```
Traceback (most recent call last):
  File "/home/egor/.local/lib/python3.8/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/home/egor/.local/lib/python3.8/site-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/home/egor/.local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 218, in request
    response = connection.request(
  File "/home/egor/.local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 106, in request
    return self.connection.request(method, url, headers, stream, ext)
  File "/home/egor/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 72, in request
    ) = self._receive_response(timeout)
  File "/home/egor/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 133, in _receive_response
    event = self._receive_event(timeout)
  File "/home/egor/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 172, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/home/egor/.local/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/egor/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/egor/.local/lib/python3.8/site-packages/qdrant_openapi_client/api_client.py", line 86, in send_inner
    response = self._client.send(request)
  File "/home/egor/.local/lib/python3.8/site-packages/httpx/_client.py", line 767, in send
    response = self._send_handling_auth(
  File "/home/egor/.local/lib/python3.8/site-packages/httpx/_client.py", line 805, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/egor/.local/lib/python3.8/site-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/home/egor/.local/lib/python3.8/site-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/egor/.local/lib/python3.8/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/egor/projects/benchmark/search_benchmark/benchmark/upload_data.py", line 76, in <module>
    benchmark.enable_indexing()
  File "/home/egor/projects/benchmark/search_benchmark/benchmark/upload_data.py", line 60, in enable_indexing
    self.client.http.collections_api.update_collection(
  File "/home/egor/.local/lib/python3.8/site-packages/qdrant_openapi_client/api/collections_api.py", line 510, in update_collection
    return self._build_for_update_collection(
  File "/home/egor/.local/lib/python3.8/site-packages/qdrant_openapi_client/api/collections_api.py", line 297, in _build_for_update_collection
    return self.api_client.request(
  File "/home/egor/.local/lib/python3.8/site-packages/qdrant_openapi_client/api_client.py", line 59, in request
    return self.send(request, type_)
  File "/home/egor/.local/lib/python3.8/site-packages/qdrant_openapi_client/api_client.py", line 76, in send
    response = self.middleware(request, self.send_inner)
  File "/home/egor/.local/lib/python3.8/site-packages/qdrant_openapi_client/api_client.py", line 179, in __call__
    return call_next(request)
  File "/home/egor/.local/lib/python3.8/site-packages/qdrant_openapi_client/api_client.py", line 88, in send_inner
    raise ResponseHandlingException(e)
qdrant_openapi_client.exceptions.ResponseHandlingException: timed out
```

**Comment by e-ivkov** [comment]
Maximum number of WAL files that I was able to detect was:
```closed-10324  closed-12388  closed-14452  closed-7228  closed-9292  open-17
closed-11356  closed-13420  closed-6196   closed-8260  open-16```

Then it was eventually optimized to:
`closed-14452  open-16  open-17`

**Comment by e-ivkov** [comment]
With 100_000 vectors and wal file size at 2mb I was able to reproduce a situation where there would remain more than 1 closed file after updates - this seems to be the bug that we want to correct.
