### ISSUE TITLE
Qdrant is giving empty response 

### ISSUE THREAD

**Issue by nithin-nk** [qdrant/qdrant#3653]
We are using qdrant to store our vectors. We deploy Qdrant using official helm charts to the Kubernetes cluster. We are using the async client to connect to Qdrant.

`aclient = qdrant_client.AsyncQdrantClient(url=qdrant_endpoint, timeout=360)`

Out of 10 requests 2 or 3 requests failed with the following error

```
ERROR - llama_index.py - Traceback (most recent call last):
  File "/app/src/api/routers/llama_index.py", line 50, in query_llama_index_retrieval
    response = await query_doc_async(query_engine, query_engine_c,req_body.question, llm, req_body.email, req_body.thread_id, req_body.app_type, req_body.object_id)
  File "/app/src/api/Document_Retrieval.py", line 146, in query_doc_async
    response = await run_async(query_engine, query_engine_c, question, llm)
  File "/app/src/api/Document_Retrieval.py", line 178, in run_async
    responses_scores = await asyncio.gather(query_util_async(query_engine, question, llm),
  File "/app/src/api/Document_Retrieval.py", line 218, in query_util_async
    response = await query_engine.aquery(question)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/base_query_engine.py", line 36, in aquery
    return await self._aquery(str_or_query_bundle)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/query_engine/retriever_query_engine.py", line 185, in _aquery
    nodes = await self.aretrieve(query_bundle)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/query_engine/retriever_query_engine.py", line 130, in aretrieve
    nodes = await self._retriever.aretrieve(query_bundle)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/base_retriever.py", line 72, in aretrieve
    nodes = await self._aretrieve(query_bundle)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 99, in _aretrieve
    return await self._aget_nodes_with_embeddings(query_bundle)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 171, in _aget_nodes_with_embeddings
    query_result = await self._vector_store.aquery(query, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/qdrant.py", line 564, in aquery
    response = await self._aclient.search(
  File "/usr/local/lib/python3.10/dist-packages/qdrant_client/async_qdrant_client.py", line 312, in search
    return await self._client.search(
  File "/usr/local/lib/python3.10/dist-packages/qdrant_client/async_qdrant_remote.py", line 368, in search
    search_result = await self.http.points_api.search_points(
  File "/usr/local/lib/python3.10/dist-packages/qdrant_client/http/api/points_api.py", line 1039, in search_points
    return await self._build_for_search_points(
  File "/usr/local/lib/python3.10/dist-packages/qdrant_client/http/api_client.py", line 146, in request
    return await self.send(request, type_)
  File "/usr/local/lib/python3.10/dist-packages/qdrant_client/http/api_client.py", line 169, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 408 (Request Timeout)
Raw response content:
b''
```
How to fix this error? 
Python client version is 1.7.3

**Comment by timvisee** [comment]
Your requests time out, maybe the requests are too expensive.

Could you share a snippet of what kinds of request you're trying to make?

**Comment by nithin-nk** [comment]
We are using llama index to query Qdrant database. We are doing vector similarity search

**Comment by generall** [comment]
Hi @nithin-nk, I am afraid there is not enough context in your issue to suggest you anything useful.
