### ISSUE TITLE
Panic on concurrent requests with filters

### ISSUE THREAD

**Issue by Axelwickm** [qdrant/qdrant#3737]
I'm doing concurrent loading (with Pytorch Dataloader), meaning that I'm doing many calls with many quite restrictive filters. Disabling the filter, or removing the concurrency, fixes the issue.

## Current Behavior

The server ends up panicking, and I get this stacktrace after a couple of seconds of it running as intended:
```
qdrant-1  | 2024-03-01T13:18:29.767703Z ERROR qdrant::startup: Panic backtrace:
qdrant-1  |    0: qdrant::startup::setup_panic_hook::{{closure}}
qdrant-1  |    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
qdrant-1  |    2: std::panicking::rust_panic_with_hook
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
qdrant-1  |    3: std::panicking::begin_panic_handler::{{closure}}
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
qdrant-1  |    4: std::sys_common::backtrace::__rust_end_short_backtrace
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
qdrant-1  |    5: rust_begin_unwind
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
qdrant-1  |    6: core::panicking::panic_fmt
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
qdrant-1  |    7: core::panicking::panic
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
qdrant-1  |    8: collection::common::batching::batch_requests
qdrant-1  |    9: actix_web::handler::handler_service::{{closure}}::{{closure}}
qdrant-1  |   10: <actix_web::resource::Resource<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}
qdrant-1  |   11: <actix_web::middleware::compress::CompressResponse<S,B> as core::future::future::Future>::poll
qdrant-1  |   12: <actix_web::middleware::condition::ConditionMiddlewareFuture<E,D> as core::future::future::Future>::poll
qdrant-1  |   13: <actix_cors::middleware::CorsMiddleware<S> as actix_service::Service<actix_web::service::ServiceRequest>>::call::{{closure}}
qdrant-1  |   14: <qdrant::actix::actix_telemetry::ActixTelemetryService<S> as actix_service::Service<actix_web::service::ServiceRequest>>::call::{{closure}}
qdrant-1  |   15: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
qdrant-1  |   16: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
qdrant-1  |   17: tokio::runtime::task::raw::poll
qdrant-1  |   18: tokio::task::local::LocalSet::tick
qdrant-1  |   19: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
qdrant-1  |   20: std::sys_common::backtrace::__rust_begin_short_backtrace
qdrant-1  |   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
qdrant-1  |   22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
qdrant-1  |   23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
qdrant-1  |   24: std::sys::unix::thread::Thread::new::thread_start
qdrant-1  |              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
qdrant-1  |   25: <unknown>
qdrant-1  |   26: clone
```

The client reacts like this:
```
Traceback (most recent call last):
  File "/app/backend/matching/datasets.py", line 307, in <module>
    for data in dataloader:
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
qdrant_client.http.exceptions.ResponseHandlingException: Caught ResponseHandlingException in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/opt/conda/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 101, in send_inner
    response = self._client.send(request)
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/conda/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/opt/conda/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 53, in fetch
    data = self.dataset[possibly_batched_index]
  File "/app/backend/matching/datasets.py", line 205, in __getitem__
    return self.get_by_id(query[0], query[1])
  File "/app/backend/matching/datasets.py", line 172, in get_by_id
    results = qdrant_db.search_in_qdrant(
  File "/app/backend/qdrant_db.py", line 207, in search_in_qdrant
    results = client.search_batch(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 243, in search_batch
    return self._client.search_batch(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 369, in search_batch
    http_res: List[List[models.ScoredPoint]] = self.http.points_api.search_batch_points(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 1354, in search_batch_points
    return self._build_for_search_batch_points(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 568, in _build_for_search_batch_points
    return self.api_client.request(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
    return self.send(request, type_)
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 91, in send
    response = self.middleware(request, self.send_inner)
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 200, in __call__
    return call_next(request)
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 103, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: Server disconnected without sending a response.
```

## Steps to Reproduce

I have everything in proprietary wrappers, and have to attend to my client, so not gonna be able to give in-depth reproduction instructions at this moment. I can supply more in-depth reproduction instructions later on request if this isn't sufficient.

I'm using this filter:
```python
scroll_filter = qdrant_client.models.Filter(
    must=[
        qdrant_client.models.FieldCondition(
            key="profile_id",
            match=qdrant_client.models.MatchAny(any=[profile_id])
        )
    ]
)
```

And am using search_batch:
```python
 search_queries = [
    models.SearchRequest(
        vector=vector,
        limit=top_k,
        with_vector=with_vector,
        with_payload=with_payload,
        score_threshold=minimum_score,
        filter=sf
    ) for vector, sf in zip(query, scroll_filter)
 ]

  results = client.search_batch(
      collection_name=collection,
      requests=search_queries,
  )
```
with
```
minimum_score=0.3
top_k=10000000
with_vector=False
with_payload=True
```

## Context (Environment)

I'm running qdrant-client 1.7.3, and am have tried using the docker images for `qdrant/qdrant:dev`, `v1.7.4`, `v1.7.0`.

The issue does not seem to be present if I use `qdrant/qdrant:v1.6.1`.

I have no specified `/qdrant/config/production.yaml`

**Comment by xzfc** [comment]
Hi. Thanks for the report.

I could reproduce the panic when `requests` is an empty array. Could you please check if this is the case in your setup?

While an empty request doesn't make much sense, qdrant shouldn't panic while performing it, and we should fix it.

**Comment by Axelwickm** [comment]
Yup, you are completely right. You fix my code, I fix yours. Beautiful.
