### ISSUE TITLE
Error: Connection refused when running Docker image on gRPC port 6334

### ISSUE THREAD

**Issue by Satyamcoretus** [qdrant/qdrant#4144]
When attempting to run the Docker image for the qdrant_client on gRPC port 6334, I encounter the following error:

## Current Behavior
qdrant_client.http.exceptions.ResponseHandlingException: [Errno 111] Connection refused

 example, or an unambiguous set of steps to -->

**Steps to Reproduce:**

1. Run the Docker image with the following command: sudo docker run -p 6334:6334   -v $(pwd)/Qdrant_storage_grpc:/qdrant/storage qdrant/qdrant
3. Access the service or perform an action that triggers the error.

**Expected Behavior:**
I was expecting that the connection would be successful so that I can access my collections and all necessary data without encountering any errors.

**Actual Behavior:**
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 103, in send_inner
    response = self._client.send(request)
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/coretus-15/Satyam/Chatbot/testing2.py", line 13, in <module>
    client.create_collection('thepla',vectors_config=vector_configuration)
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1730, in create_collection
    return self._client.create_collection(
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 2261, in create_collection
    result: Optional[bool] = self.http.collections_api.create_collection(
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 1170, in create_collection
    return self._build_for_create_collection(
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 116, in _build_for_create_collection
    return self.api_client.request(
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 76, in request
    return self.send(request, type_)
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 93, in send
    response = self.middleware(request, self.send_inner)
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 202, in __call__
    return call_next(request)
  File "/home/coretus-15/Satyam/Chatbot/venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 105, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: [Errno 111] Connection refused

**Additional Information:**

- Operating System: Ubuntu 22.04.4 LTS 64 bit
- Docker Version: 24.0.
- Qdrant - qdrant_client 1.9.0

**Comment by timvisee** [comment]
Could you share the snippet you use to set up the Qdrant client, which connects to the instance?

**Comment by Satyamcoretus** [comment]
@timvisee 

from qdrant_client import QdrantClient,models
from qdrant_client.models import Distance
from testing import query_vector

vector_configuration = {
            "test_vectors": models.VectorParams(
                distance=Distance.COSINE,size=768,on_disk=True
            )

}
client = QdrantClient(url='http://localhost:6333')

client.create_collection('thepla',vectors_config=vector_configuration)
client.upsert(
    collection_name="thepla",
    points=[
        models.PointStruct(
            id=1,
            payload={
                "color": "brown",
            },
            vector={
                'test_vectors' : query_vector
            }
        )
        ]
)


search = client.search(
    collection_name="dhokla",
    query_vector=("test_vectors", query_vector),
    limit=4,
    with_vectors=True,
    with_payload=True

)
for hit in search:
    print(hit.payload, "score:", hit.score,hit.vector)

It is working fine on this port - 
sudo docker run -p 6333:6333   -v $(pwd)/Qdrant_storage_grpc:/qdrant/storage qdrant/qdrant

but when i tried the same command on this port 6334, then i get the same error mentioned above.

client = QdrantClient(url='http://localhost:6333',grpc_port=6334)

client.create_collection('thepla',vectors_config=vector_configuration)
client.upsert(
    collection_name="thepla",
    points=[
        models.PointStruct(
            id=1,
            payload={
                "color": "brown",
            },
            vector={
                'test_vectors' : query_vector
            }
        )
        ]
)


search = client.search(
    collection_name="dhokla",
    query_vector=("test_vectors", query_vector),
    limit=4,
    with_vectors=True,
    with_payload=True

)
for hit in search:
    print(hit.payload, "score:", hit.score,hit.vector)

**Comment by Satyamcoretus** [comment]
@timvisee 
I forgot that default behavior is prefer_grpc = False, when i set it as this -

client = QdrantClient(url='http://localhost:6333',prefer_grpc = True,grpc_port=6334)

then I started getting this error-
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:6334: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-04-30T16:29:51.138089973+05:30", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:6334: Failed to connect to remote host: Connection refused"}"
>

**Comment by Satyamcoretus** [comment]
@timvisee 
THANK YOU
It is resolved now
