### ISSUE TITLE
Python create_snapshot api returns ReadTimeout when creating snapshot on big size snapshot

### ISSUE THREAD

**Issue by BlueBlueSummer** [qdrant/qdrant#4802]
Python create_snapshot api returns ReadTimeout when creating snapshot on big size collection(3Gi)
## Current Behavior
Throw ReadTimeout error

## Steps to Reproduce
from qdrant_client import QdrantClient
node="http://****:6333"
collection="search-system"
client = QdrantClient(url=node)
client.create_snapshot(collection_name=collection, wait=True)

qdrant version: v1.10.1
qdrant-client==1.10.1

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 106, in send_inner
    response = self._client.send(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 2289, in create_snapshot
    return self._client.create_snapshot(collection_name=collection_name, wait=wait, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/qdrant_remote.py", line 2755, in create_snapshot
    return self.openapi_client.collections_api.create_snapshot(
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api/collections_api.py", line 1228, in create_snapshot
    return self._build_for_create_snapshot(
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api/collections_api.py", line 233, in _build_for_create_snapshot
    return self.api_client.request(
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 79, in request
    return self.send(request, type_)
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 96, in send
    response = self.middleware(request, self.send_inner)
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 205, in __call__
    return call_next(request)
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 108, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: timed out

**Comment by generall** [comment]
please refer to the documentation: https://qdrant.tech/documentation/tutorials/create-snapshot/#create-and-download-snapshots
