### ISSUE TITLE
Flaky test_resharding_concurrent_updates 

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#4808]
The test is flaky on CI.

```
----------------------------- Captured stderr call -----------------------------
Process Process-8:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/test_resharding.py", line 1069, in upsert_points_throttled
    upsert_random_points(peer_url, count, collection_name, offset=offset)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/fixtures.py", line 74, in upsert_random_points
    assert_http_ok(r_batch)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/assertions.py", line 10, in assert_http_ok
    raise Exception(
Exception: HTTP request to http://127.0.0.1:51939/collections/test_collection/points?wait=true&ordering=weak failed with status code 500 after 216.436871s with response body:
{'status': {'error': 'Service internal error: 1 out of 2 shards failed to apply operation. First error captured: Service internal error: Some replica of shard 0 failed to apply operation and deactivation timed out after 30 seconds. Consistency of this update is not guaranteed. Please retry. Failed peer: 6354009439270588, error: Operation Cancelled: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }'}, 'time': 216.432880964}
Process Process-6:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/test_resharding.py", line 1069, in upsert_points_throttled
    upsert_random_points(peer_url, count, collection_name, offset=offset)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/fixtures.py", line 74, in upsert_random_points
    assert_http_ok(r_batch)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/assertions.py", line 10, in assert_http_ok
    raise Exception(
Exception: HTTP request to http://127.0.0.1:39049/collections/test_collection/points?wait=true&ordering=weak failed with status code 500 after 216.41922s with response body:
{'status': {'error': 'Service internal error: Some replica of shard 1 failed to apply operation and deactivation timed out after 30 seconds. Consistency of this update is not guaranteed. Please retry. Failed peer: 6354009439270588, error: Operation Cancelled: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }'}, 'time': 216.415471368}
Process Process-9:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/test_resharding.py", line 1069, in upsert_points_throttled
    upsert_random_points(peer_url, count, collection_name, offset=offset)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/fixtures.py", line 74, in upsert_random_points
    assert_http_ok(r_batch)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/assertions.py", line 10, in assert_http_ok
    raise Exception(
Exception: HTTP request to http://127.0.0.1:39049/collections/test_collection/points?wait=true&ordering=weak failed with status code 500 after 216.461057s with response body:
{'status': {'error': 'Service internal error: Some replica of shard 2 failed to apply operation and deactivation timed out after 30 seconds. Consistency of this update is not guaranteed. Please retry. Failed peer: 6354009439270588, error: Operation Cancelled: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }'}, 'time': 216.456940908}
Process Process-7:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/test_resharding.py", line 1069, in upsert_points_throttled
    upsert_random_points(peer_url, count, collection_name, offset=offset)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/fixtures.py", line 74, in upsert_random_points
    assert_http_ok(r_batch)
  File "/home/runner/work/qdrant/qdrant/tests/consensus_tests/assertions.py", line 10, in assert_http_ok
    raise Exception(
Exception: HTTP request to http://127.0.0.1:35625/collections/test_collection/points?wait=true&ordering=weak failed with status code 500 after 216.540308s with response body:
{'status': {'error': 'Service internal error: Some replica of shard 0 failed to apply operation and deactivation timed out after 30 seconds. Consistency of this update is not guaranteed. Please retry. Failed peer: 3809396070177349, error: Operation Cancelled: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }'}, 'time': 216.536113838}
--------------------------- Captured stdout teardown ---------------------------

Killing 63662
Killing 63687
Killing 63688
=============================== warnings summary ===============================
tests/consensus_tests/test_resharding.py::test_resharding_concurrent_updates
  /home/runner/.cache/pypoetry/virtualenvs/qdrant-test-deps-FyR9sbRm-py3.11/lib/python3.11/site-packages/_pytest/python.py:1792: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
  Plugin: schemathesis, Hook: pytest_pyfunc_call
  Exception: Timeout waiting for condition check_collection_resharding_operations_count to be satisfied in 120 seconds
  For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/consensus_tests/test_resharding.py::test_resharding_concurrent_updates - Exception: Timeout waiting for condition check_collection_resharding_operations_count to be satisfied in 120 seconds
```

e.g. https://github.com/qdrant/qdrant/actions/runs/10214228278/job/28261193622#step:11:312
logs: 
[consensus-test-logs.zip](https://github.com/user-attachments/files/16470043/consensus-test-logs.zip)

**Comment by agourlay** [comment]
The test has been disabled for the time being https://github.com/qdrant/qdrant/pull/4811
