### ISSUE TITLE
Flaky test correct_positive_order

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#4907]
```
--- TRY 3 STDERR:        segment vector_storage::query::reco_query::test::correct_positive_order ---
thread 'vector_storage::query::reco_query::test::correct_positive_order' panicked at lib/segment/src/vector_storage/query/reco_query.rs:188:13:
assertion `left == right` failed
  left: Less
 right: Equal
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'vector_storage::query::reco_query::test::correct_positive_order' panicked at lib/segment/src/vector_storage/query/reco_query.rs:188:13:
assertion `left == right` failed
  left: Less
 right: Equal
thread 'vector_storage::query::reco_query::test::correct_positive_order' panicked at lib/segment/src/vector_storage/query/reco_query.rs:188:13:
assertion `left == right` failed
  left: Less
 right: Equal
thread 'vector_storage::query::reco_query::test::correct_positive_order' panicked at lib/segment/src/vector_storage/query/reco_query.rs:150:5:
Test failed: assertion `left == right` failed
  left: Less
 right: Equal.
minimal failing input: a = 95.398964, b = 95.40226
	successes: 0
	local rejects: 0
	global rejects: 0
```

**Comment by coszio** [comment]
Should be resolved by #4911
