### ISSUE TITLE
Pywin32 dependency

### ISSUE THREAD

**Issue by ALysyt** [qdrant/qdrant#5212]
Since this repo depends on pywin32 library, is there a way to use this repo on a linux based machine?

**Comment by timvisee** [comment]
Yes! Qdrant runs on all the major platforms, being Linux, macOS and Windows.

There's no hard dependency on `pywin32` and would only be used for a specific set of tests on Windows.

**Comment by ALysyt** [comment]
can you please explain this error to me? without pywintypes the library does not run

Traceback (most recent call last):
  File "C:\Users\olexi\Desktop\Apps\NexsoftMagister\MagisterAPI\main.py", line 8, in <module>
    from vectordb.indexer import setup_qdrant, process_java_class, process_pom
  File "C:\Users\olexi\Desktop\Apps\NexsoftMagister\MagisterAPI\vectordb\indexer.py", line 5, in <module>
    from qdrant_client import QdrantClient
  File "C:\Users\olexi\Desktop\Apps\MagisterAPI\.venv\Lib\site-packages\qdrant_client\__init__.py", line 1, in <module>
    from .async_qdrant_client import AsyncQdrantClient as AsyncQdrantClient
  File "C:\Users\olexi\Desktop\Apps\MagisterAPI\.venv\Lib\site-packages\qdrant_client\async_qdrant_client.py", line 31, in <module>
    from qdrant_client.local.async_qdrant_local import AsyncQdrantLocal
  File "C:\Users\olexi\Desktop\Apps\MagisterAPI\.venv\Lib\site-packages\qdrant_client\local\async_qdrant_local.py", line 36, in <module>
    import portalocker
  File "C:\Users\olexi\Desktop\Apps\MagisterAPI\.venv\Lib\site-packages\portalocker\__init__.py", line 1, in <module>
    from . import __about__, constants, exceptions, portalocker
  File "C:\Users\olexi\Desktop\Apps\MagisterAPI\.venv\Lib\site-packages\portalocker\portalocker.py", line 22, in <module>
    import pywintypes
ModuleNotFoundError: No module named 'pywintypes'

![Untitled](https://github.com/user-attachments/assets/19016a7a-47ac-4283-851f-abd4e7491dc9)

**Comment by timvisee** [comment]
> (...) is there a way to use this repo on a linux based machine?

You mention a Linux based machine.

However, your error message shows that you're running on a Windows based platform.

Based on the error I believe pywin isn't properly installed.

**Comment by ALysyt** [comment]
i cant install pywin32 if i am on a linux machine
anyway i think i've solved it thanks

**Comment by timvisee** [comment]
> i cant install pywin32 if i am on a linux machine

You should not see the above error message if running on a Linux machine. Thus I don't expect any issues there.
