### ISSUE TITLE
Can't initialize consensus: Failed to initialize Consensus for new Raft state

### ISSUE THREAD

**Issue by sivaguru-pat** [qdrant/qdrant#757]
I have been trying to deploy distributed setup in docker-compose facing this issue

**docker-compose.yaml**
```
version: "3.9"
networks:
  qdrant:
    ipam:
      config:
        - subnet: 172.69.2.0/24
services:
  first-peer:
    image: qdrant/qdrant:v0.8.2
    command: ./qdrant --uri 'http://172.69.2.5:6335'
    networks:
      qdrant:
        ipv4_address: 172.69.2.5
    ports:
      - "6333:6333"
      - "6334:6334"
      

    environment:
      - RUST_BACKTRACE=full
    volumes:
      - ./config:/qdrant/config/
    
  second-peer:
    image: qdrant/qdrant:v0.8.2
    command: ./qdrant --bootstrap 'http://172.69.2.5:6335' 
    networks:
      qdrant:
        ipv4_address: 172.69.2.6
    
    volumes:
      - ./config:/qdrant/config/
    depends_on:
      - first-peer
    links: 
      - first-peer  
    environment:
      - RUST_BACKTRACE=full
    restart: unless-stopped  
```
**config**
```
debug: false
log_level: INFO
cluster:
  enabled: true
  p2p:
    port: 6335

  consensus:
    tick_period_ms: 100
service:
  enable_cors: true
  grpc_port: 6334
  host: 0.0.0.0
  http_port: 6333
  max_request_size_mb: 32
  max_workers: 0
storage:
  hnsw_index:
    ef_construct: 100
    full_scan_threshold: 10000
    m: 16
  optimizers:
    default_segment_number: 5
    deleted_threshold: 0.2
    flush_interval_sec: 1
    indexing_threshold: 20000
    max_optimization_threads: 0
    max_segment_size: 200000
    memmap_threshold: 50000
    payload_indexing_threshold: 10000
    vacuum_min_vector_number: 1000
  performance:
    max_search_threads: 0
  storage_path: ./storage
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0
```

**logs**
```
first-peer_1   |            _                 _    
first-peer_1   |   __ _  __| |_ __ __ _ _ __ | |_  
first-peer_1   |  / _` |/ _` | '__/ _` | '_ \| __| 
first-peer_1   | | (_| | (_| | | | (_| | | | | |_  
first-peer_1   |  \__, |\__,_|_|  \__,_|_| |_|\__| 
first-peer_1   |     |_|                           
first-peer_1   | 
first-peer_1   | Access web UI at https://ui.qdrant.tech/?v=v0.8.2
first-peer_1   | 
first-peer_1   | [2022-06-28T08:19:49.664Z INFO  storage::content_manager::consensus_state] Initializing new raft state at ./storage/raft_state
first-peer_1   | [2022-06-28T08:19:49.674Z INFO  raft::raw_node] RawNode created with id 8936407191798413078., raft_id: 8936407191798413078, id: 8936407191798413078
second-peer_1  |            _                 _    
second-peer_1  |   __ _  __| |_ __ __ _ _ __ | |_  
second-peer_1  |  / _` |/ _` | '__/ _` | '_ \| __| 
second-peer_1  | | (_| | (_| | | | (_| | | | | |_  
second-peer_1  |  \__, |\__,_|_|  \__,_|_| |_|\__| 
second-peer_1  |     |_|                           
second-peer_1  | 
second-peer_1  | Access web UI at https://ui.qdrant.tech/?v=v0.8.2
second-peer_1  | 
first-peer_1   | [2022-06-28T08:19:49.675Z INFO  qdrant::tonic] Qdrant gRPC listening on 6334
second-peer_1  | [2022-06-28T08:19:50.061Z INFO  storage::content_manager::consensus_state] Initializing new raft state at ./storage/raft_state
first-peer_1   | [2022-06-28T08:19:49.695Z INFO  actix_server::builder] Starting 11 workers
first-peer_1   | [2022-06-28T08:19:49.695Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
first-peer_1   | [2022-06-28T08:19:50.076Z ERROR qdrant] Consensus stopped with error: raft: proposal dropped
second-peer_1  | thread 'main' panicked at 'Can't initialize consensus: Failed to initialize Consensus for new Raft state
second-peer_1  | 
second-peer_1  | Caused by:
second-peer_1  |     0: Failed to add peer to known
second-peer_1  |     1: status: Internal, message: "Failed to add peer: Service internal error: Waiting for consensus operation commit failed. Timeout set at: 10 seconds", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 28 Jun 2022 08:20:00 GMT", "content-length": "0"} }', src/main.rs:139:10
second-peer_1  | stack backtrace:
second-peer_1  |    0:     0x558eb37ddb0d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
second-peer_1  |    1:     0x558eb37ddb0d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
second-peer_1  |    2:     0x558eb37ddb0d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
second-peer_1  |    3:     0x558eb37ddb0d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
second-peer_1  |    4:     0x558eb3801c8c - core::fmt::write::hba4337c43d992f49
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
second-peer_1  |    5:     0x558eb37d7071 - std::io::Write::write_fmt::heb73de6e02cfabed
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
second-peer_1  |    6:     0x558eb37df565 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
second-peer_1  |    7:     0x558eb37df565 - std::sys_common::backtrace::print::h426700d6240cdcc2
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
second-peer_1  |    8:     0x558eb37df565 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
second-peer_1  |    9:     0x558eb37df219 - std::panicking::default_hook::h2e88d02087fae196
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
second-peer_1  |   10:     0x558eb37dfab2 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
second-peer_1  |   11:     0x558eb37df997 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
second-peer_1  |   12:     0x558eb37ddfc4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
second-peer_1  |   13:     0x558eb37df6c9 - rust_begin_unwind
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
second-peer_1  |   14:     0x558eb27f7883 - core::panicking::panic_fmt::h366d3a309ae17c94
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
second-peer_1  |   15:     0x558eb27f7973 - core::result::unwrap_failed::hddd78f4658ac7d0f
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
second-peer_1  |   16:     0x558eb2c28bbc - qdrant::main::h5f048b6e55419a20
second-peer_1  |   17:     0x558eb2975913 - std::sys_common::backtrace::__rust_begin_short_backtrace::h682ebb9105c878fc
second-peer_1  |   18:     0x558eb28f86bd - std::rt::lang_start::{{closure}}::hb5ec173a9a2fe0b9
second-peer_1  |   19:     0x558eb37d0ede - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
second-peer_1  |   20:     0x558eb37d0ede - std::panicking::try::do_call::hf2ad5355fcafe775
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
second-peer_1  |   21:     0x558eb37d0ede - std::panicking::try::h0a63ac363423e61e
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
second-peer_1  |   22:     0x558eb37d0ede - std::panic::catch_unwind::h18088edcecb8693a
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
second-peer_1  |   23:     0x558eb37d0ede - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
second-peer_1  |   24:     0x558eb37d0ede - std::panicking::try::do_call::hda0c61bf3a57d6e6
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
second-peer_1  |   25:     0x558eb37d0ede - std::panicking::try::hbc940e68560040a9
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
second-peer_1  |   26:     0x558eb37d0ede - std::panic::catch_unwind::haed0df2aeb3fa368
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
second-peer_1  |   27:     0x558eb37d0ede - std::rt::lang_start_internal::h9c06694362b5b80c
second-peer_1  |                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
second-peer_1  |   28:     0x558eb2c2af72 - main
second-peer_1  |   29:     0x7f3c0aef3d0a - __libc_start_main
second-peer_1  |   30:     0x558eb281600a - _start
second-peer_1  |   31:                0x0 - <unknown>
second-peer_1  | [2022-06-28T08:20:00.913Z INFO  raft::raw_node] RawNode created with id 980097074040822996., raft_id: 980097074040822996, id: 980097074040822996
second-peer_1  | [2022-06-28T08:20:00.913Z INFO  qdrant::tonic] Qdrant gRPC listening on 6334
second-peer_1  | [2022-06-28T08:20:00.932Z INFO  actix_server::builder] Starting 11 workers
second-peer_1  | [2022-06-28T08:20:00.932Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
first-peer_1   | [2022-06-28T08:30:00.127Z INFO  actix_web::middleware::logger] 172.69.2.1 "GET /cluster HTTP/1.1" 200 204 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" 0.002661
```

**Comment by agourlay** [comment]
Hi @sivaguru-pat,

It seems that your second-peer joined too fast.
When starting the cluster, it is recommended to wait for the first peer to fully bootstrap before adding nodes to the cluster.

The current service dependency used in your docker-compose does not capture the exact readiness semantic required.

The first peer is ready if its cluster API returns the following info:
- a non null `leader` field
- a non empty `peers` array

Without automation you can manually boot the containers in order:

1. `docker-compose up first-peer`
2. wait a few seconds and inspect the cluster status with GET `http://172.69.2.5:6333/cluster`
3. `docker-compose up second-peer`

Additional `second-peer` instances do not need to be added sequentially.

**Comment by sivaguru-pat** [comment]
hey @agourlay it resolved the issue
